### ISSUE TITLE
Backend Startup Failure Due to bcrypt Version Error

### ISSUE THREAD

**Issue by Sevichecc** [evroon/bracket#393]
After completing the basic backend setup, I attempted to run` ./run.sh`. However, the operation failed, potentially due to an issue related to bcrypt. How could I solve this?

Related issues: 
- https://github.com/pyca/bcrypt/issues/684
- https://foss.heptapod.net/python-libs/passlib/-/issues/190

```shell
[2023-12-18 13:53:39 +0800] [92564] [INFO] Starting gunicorn 21.2.0
[2023-12-18 13:53:39 +0800] [92564] [INFO] Listening at: http://127.0.0.1:8400 (92564)
[2023-12-18 13:53:39 +0800] [92564] [INFO] Using worker: bracket.uvicorn.RestartableUvicornWorker
[2023-12-18 13:53:39 +0800] [92569] [INFO] Booting worker with pid: 92569
 ⚠ Port 3000 is in use, trying 3001 instead.
 ⚠ Port 3001 is in use, trying 3002 instead.
   ▲ Next.js 14.0.3
   - Local:        http://localhost:3002

[2023-12-18 13:53:39,826] [bracket] [INFO] Current env: DEVELOPMENT
(trapped) error reading bcrypt version
Traceback (most recent call last):
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/passlib/handlers/bcrypt.py", line 620, in _load_backend_mixin
    version = _bcrypt.__about__.__version__
AttributeError: module 'bcrypt' has no attribute '__about__'
[2023-12-18 13:53:40 +0800] [92569] [INFO] Started server process [92569]
[2023-12-18 13:53:40 +0800] [92569] [INFO] Waiting for application startup.
[2023-12-18 13:53:40 +0800] [92569] [ERROR] Traceback (most recent call last):
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/starlette/routing.py", line 677, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/Users/seviche/Desktop/Project/bracket/backend/bracket/app.py", line 36, in lifespan
    await database.connect()
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/databases/core.py", line 112, in connect
    await self._backend.connect()
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/databases/backends/postgres.py", line 74, in connect
    self._pool = await asyncpg.create_pool(**kwargs)
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/pool.py", line 403, in _async__init__
    await self._initialize()
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/pool.py", line 430, in _initialize
    await first_ch.connect()
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/pool.py", line 128, in connect
    self._con = await self._pool._get_new_connection()
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/pool.py", line 502, in _get_new_connection
    con = await connection.connect(
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/connection.py", line 2329, in connect
    return await connect_utils._connect(
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 1017, in _connect
    raise last_error or exceptions.TargetServerAttributeNotMatched(
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 991, in _connect
    conn = await _connect_addr(
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 828, in _connect_addr
    return await __connect_addr(params, True, *args)
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 873, in __connect_addr
    tr, pr = await connector
  File "/Users/seviche/.local/share/virtualenvs/backend-uNhJPzew/lib/python3.10/site-packages/asyncpg/connect_utils.py", line 744, in _create_ssl_connection
    tr, pr = await loop.create_connection(
  File "/opt/homebrew/Cellar/python@3.10/3.10.12_1/Frameworks/Python.framework/Versions/3.10/lib/python3.10/asyncio/base_events.py", line 1084, in create_connection
    raise OSError('Multiple exceptions: {}'.format(
OSError: Multiple exceptions: [Errno 61] Connect call failed ('::1', 5432, 0, 0), [Errno 61] Connect call failed ('127.0.0.1', 5432)

[2023-12-18 13:53:40 +0800] [92569] [ERROR] Application startup failed. Exiting.
```

**Comment by Sevichecc** [comment]
Setting the bcrypt version to "4.0.1" will solve this.

**Comment by evroon** [comment]
@Sevichecc can you confirm it's no longer an issue now? I merged a fix

**Comment by Sevichecc** [comment]
@evroon Yes, I can confirm that the issue has been resolved. Thank you for the fix!c
