### ISSUE TITLE
Issue in first time databse creation

### ISSUE THREAD

**Issue by robigan** [evroon/bracket#520]
```
Traceback (most recent call last):
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/starlette/routing.py", line 734, in lifespan
    async with self.lifespan_context(app) as maybe_state:
  File "/usr/lib/python3.10/contextlib.py", line 199, in __aenter__
    return await anext(self.gen)
  File "/home/robigan/Documents/Source/bracket/backend/bracket/app.py", line 51, in lifespan
    run_migrations()
  File "/home/robigan/Documents/Source/bracket/backend/bracket/app.py", line 42, in run_migrations
    command.upgrade(alembic_cfg, "head")
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/command.py", line 403, in upgrade
    script.run_env()
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/script/base.py", line 583, in run_env
    util.load_python_file(self.dir, "env.py")
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 95, in load_python_file
    module = load_module_py(module_id, path)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/util/pyfiles.py", line 113, in load_module_py
    spec.loader.exec_module(module)  # type: ignore
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/robigan/Documents/Source/bracket/backend/alembic/env.py", line 47, in <module>
    run_migrations_online()
  File "/home/robigan/Documents/Source/bracket/backend/alembic/env.py", line 39, in run_migrations_online
    context.run_migrations()
  File "<string>", line 8, in run_migrations
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/runtime/environment.py", line 948, in run_migrations
    self.get_context().run_migrations(**kw)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/runtime/migration.py", line 627, in run_migrations
    step.migration_fn(**kw)
  File "/home/robigan/Documents/Source/bracket/backend/alembic/versions/6458e0bc3e9d_add_stages_table.py", line 23, in upgrade
    op.create_table(
  File "<string>", line 8, in create_table
  File "<string>", line 3, in create_table
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/operations/ops.py", line 1311, in create_table
    return operations.invoke(op)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/operations/base.py", line 445, in invoke
    return fn(self, operation)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/operations/toimpl.py", line 131, in create_table
    operations.impl.create_table(table)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/alembic/ddl/impl.py", line 363, in create_table
    table.dispatch.before_create(
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/event/attr.py", line 346, in __call__
    fn(*args, **kw)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 875, in __call__
    return getattr(self.target, self.name)(*arg, **kw)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2206, in _on_table_create
    self.create(bind=bind, checkfirst=checkfirst)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2111, in create
    bind._run_ddl_visitor(self.EnumGenerator, self, checkfirst=checkfirst)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2221, in _run_ddl_visitor
    visitorcallable(self.dialect, self, **kwargs).traverse_single(element)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/sql/visitors.py", line 524, in traverse_single
    return meth(obj, **kw)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/dialects/postgresql/base.py", line 2152, in visit_enum
    self.connection.execute(CreateEnumType(enum))
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1385, in execute
    return meth(self, multiparams, params, _EMPTY_EXECUTION_OPTS)
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/sql/ddl.py", line 80, in _execute_on_connection
    return connection._execute_ddl(
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1477, in _execute_ddl
    ret = self._execute_context(
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1953, in _execute_context
    self._handle_dbapi_exception(
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 2134, in _handle_dbapi_exception
    util.raise_(
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 1910, in _execute_context
    self.dialect.do_execute(
  File "/home/robigan/.local/share/virtualenvs/backend-j0cBvc18/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 736, in do_execute
    cursor.execute(statement, parameters)
sqlalchemy.exc.ProgrammingError: (psycopg2.errors.DuplicateObject) type "stage_type" already exists

[SQL: CREATE TYPE stage_type AS ENUM ('SINGLE_ELIMINATION', 'SWISS', 'SWISS_DYNAMIC_TEAMS', 'ROUND_ROBIN')]
(Background on this error at: https://sqlalche.me/e/14/f405)
```

**Comment by robigan** [comment]
Furhter investigation tells me that there's a mismatch between stage_items and stage table on where this property should be.

**Comment by robigan** [comment]
Issue is located in [6458e0bc3e9d_add_stages_table](https://github.com/robigan/bracket/blob/469316efd46441ac6621c468a313985e13629a11/backend/alembic/versions/6458e0bc3e9d_add_stages_table.py) as the trace table shows. But there seems to be an even larger mismatch between migrations.

**Comment by evroon** [comment]
It's not supposed to run those old migrations, I will look into it

**Comment by evroon** [comment]
I fixed it now, can you test it by running the db initialization on latest master?

**Comment by robigan** [comment]
> I fixed it now, can you test it by running the db initialization on latest master? @robigan 

I can, I need to go right now but my associates @SoneNiko or @babeuh might test

**Comment by robigan** [comment]
> I fixed it now, can you test it by running the db initialization on latest master? @robigan

Tested, it works for first time setup
