### ISSUE TITLE
Frontend Internal server error 500 ⨯ Error: next-i18next was unable to find a user config at /app/next-i18next.config.js

### ISSUE THREAD

**Issue by flexhd41** [evroon/bracket#549]
Hey i was trying to get this setup using docker and i am getting this in the logs of the frontend as well as error 500 on the website itself 
```
 ⨯ Error: next-i18next was unable to find a user config at /app/next-i18next.config.js
    at _callee$ (/app/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:110:17)
    at tryCatch (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:45:16)
    at Generator.<anonymous> (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:133:17)
    at Generator.next (/app/node_modules/@babel/runtime/helpers/regeneratorRuntime.js:74:21)
    at asyncGeneratorStep (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:3:24)
    at _next (/app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:22:9)
    at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:27:7
    at new Promise (<anonymous>)
    at /app/node_modules/@babel/runtime/helpers/asyncToGenerator.js:19:12
react-i18next:: You will need to pass in an i18next instance by using initReactI18next
    at serverSideTranslations (/app/node_modules/next-i18next/dist/commonjs/serverSideTranslations.js:183:17)
```

**Comment by evroon** [comment]
Ah I can reproduce, it might be a problem caused by https://github.com/evroon/bracket/pull/498
@robigan do you know whether it's because this file might not be copied [here](https://github.com/evroon/bracket/blob/master/frontend/Dockerfile#L27-L31)?

**Comment by robigan** [comment]
> Ah I can reproduce, it might be a problem caused by https://github.com/evroon/bracket/pull/498
> 
> @robigan do you know whether it's because this file might not be copied [here](https://github.com/evroon/bracket/blob/master/frontend/Dockerfile#L27-L31)?

Yup, we have a commit in my fork with this fix. I'm kinda estranged that this didn't show up in production and/or testing but it might be our stack that failed. I've been meaning to PT into here but I've been swamped with school work. I'll PR ASAP

**Comment by robigan** [comment]
Additionally, I didn't see the need for next.config.js in the official example by Next.js, but I may have glossed over that.
